use_frameworks!

target 'HandyNoti_Example' do
  pod 'HandyNoti', :path => '../'

  target 'HandyNoti_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
